name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update and Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-utils
        sudo apt-get install -y --no-install-recommends sudo ca-certificates pkg-config curl wget bzip2 xz-utils make git gnupg
        sudo apt-get clean

    - name: Install devkitPro
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x ./install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        rm install-devkitpro-pacman

    - name: Install 3DS Toolchain
      run: |
        sudo dkp-pacman -Syyu --noconfirm 3ds-dev
        sudo dkp-pacman -Scc --noconfirm
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      env:
        DEVKITPRO: /opt/devkitpro
      run: make